[build]
  command = "npm run build" # Replace with your build command

[[headers]]
  for = "/*"
  [headers.values]
    X-User-Id = "12345" # Set your custom user ID here or leave it blank

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
