# netlify.toml

[build]
  command = "npm run build"  # Adjust this command based on your Next.js build script
  publish = "out"           # Adjust the output directory as needed

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"   # Allow requests from any origin (use cautiously)
    User = "Custom-User-Value"         # Custom 'User' header value
    # Add other headers as needed

[[redirects]]
  from = "/old-route"
  to = "/new-route"
  status = 301
  force = true

# Add more redirects and headers configurations as needed
